export const MEETING_ROOM_ORDER = "MEETING_ROOM";
export const EVENT = "EVENT"
export const VIRTUAL_OFFICE_ORDER = "VIRTUAL_OFFICE";
export const CATERING_ORDER = "CATERING";
export const CAFE_ORDER = "CAFE";
export const COWORKING_SPACE_ORDER = "COWORKING_SPACE"
export const PACKAGE_ORDER_TYPES = [
  MEETING_ROOM_ORDER,
  VIRTUAL_OFFICE_ORDER,
  COWORKING_SPACE_ORDER,
];